server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/test??serverTimezone=UTC
    username: root
    password: nnk82661
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
